"""
Swift Code Generation for iOS Projects
========================================

Generates production-ready Swift code following FORGE patterns:
- @Observable ViewModels (iOS 17+)
- Actor-based services (Swift 6 concurrency)
- SwiftUI views with proper state management
- MVVM architecture compliance

Architecture:
- ViewModels: @Observable, no SwiftUI imports
- Services: actor for thread safety, async/await patterns
- Views: SwiftUI, minimal logic, delegate to ViewModels
- Models: SwiftData @Model when persistence needed
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Literal


class SwiftType(Enum):
    """Swift type categories."""

    STRING = "String"
    INT = "Int"
    BOOL = "Bool"
    DOUBLE = "Double"
    DATE = "Date"
    OPTIONAL_STRING = "String?"
    OPTIONAL_INT = "Int?"
    ARRAY_STRING = "[String]"
    CUSTOM = "Custom"


@dataclass
class Property:
    """Swift property definition."""

    name: str
    type: str
    default_value: str | None = None
    is_published: bool = False  # For @Published (old pattern)
    is_optional: bool = False
    access: Literal["public", "private", "internal"] = "public"


@dataclass
class Method:
    """Swift method definition."""

    name: str
    parameters: list[tuple[str, str]] = field(default_factory=list)  # (name, type)
    return_type: str = "Void"
    is_async: bool = False
    throws: bool = False
    access: Literal["public", "private", "internal"] = "public"
    body: str = "// NOTE: Implement method body"

@dataclass
class ViewModelSpec:
    """ViewModel specification."""

    name: str  # e.g., "Auth" generates "AuthViewModel"
    properties: list[Property] = field(default_factory=list)
    methods: list[Method] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)  # Service names


@dataclass
class ActorSpec:
    """Actor service specification."""

    name: str  # e.g., "Auth" generates "AuthService"
    properties: list[Property] = field(default_factory=list)
    methods: list[Method] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)  # Other actors/services


@dataclass
class ViewSpec:
    """SwiftUI view specification."""

    name: str  # e.g., "Login" generates "LoginView"
    viewmodel_name: str  # Associated ViewModel
    has_navigation: bool = True
    has_loading_state: bool = True
    has_error_state: bool = True


class SwiftCodeGen:
    """Generate Swift code following FORGE patterns."""

    def __init__(self, project_name: str):
        """
        Initialize code generator.

        Args:
            project_name: Name of the iOS project
        """
        self.project_name = project_name

    def generate_viewmodel(self, spec: ViewModelSpec) -> str:
        """
        Generate @Observable ViewModel (iOS 17+).

        Pattern:
        - @Observable macro for state management
        - No SwiftUI imports (UI-independent)
        - Dependency injection via init
        - Async methods for network/database operations

        Args:
            spec: ViewModel specification

        Returns:
            Swift source code
        """
        class_name = f"{spec.name}ViewModel"
        imports = ["Foundation", "Observation"]

        # Add dependencies to imports if needed
        if any("Service" in dep for dep in spec.dependencies):
            # Dependencies are injected, no import needed
            pass

        code = f"""//
// {class_name}.swift
// {self.project_name}
//
// Generated by FORGE iOS Harness
//

"""

        # Imports
        for imp in imports:
            code += f"import {imp}\n"

        code += "\n"

        # Class declaration
        code += f"@Observable\nfinal class {class_name} {{\n"

        # Properties
        if spec.properties:
            code += "    // MARK: - Properties\n\n"
            for prop in spec.properties:
                access_str = f"{prop.access} " if prop.access != "internal" else ""
                var_type = prop.type
                default = f" = {prop.default_value}" if prop.default_value else ""
                code += f"    {access_str}var {prop.name}: {var_type}{default}\n"
            code += "\n"

        # Dependencies (private)
        if spec.dependencies:
            code += "    // MARK: - Dependencies\n\n"
            for dep in spec.dependencies:
                code += f"    private let {self._camel_case(dep)}: {dep}\n"
            code += "\n"

        # Initializer
        code += "    // MARK: - Initialization\n\n"
        if spec.dependencies:
            params = ", ".join([f"{self._camel_case(dep)}: {dep}" for dep in spec.dependencies])
            code += f"    init({params}) {{\n"
            for dep in spec.dependencies:
                camel = self._camel_case(dep)
                code += f"        self.{camel} = {camel}\n"
            code += "    }\n"
        else:
            code += "    init() {}\n"
        code += "\n"

        # Methods
        if spec.methods:
            code += "    // MARK: - Methods\n\n"
            for method in spec.methods:
                code += self._generate_method(method, indent="    ")
                code += "\n"

        code += "}\n"

        return code

    def generate_actor(self, spec: ActorSpec) -> str:
        """
        Generate actor-based service (Swift 6 concurrency).

        Pattern:
        - actor for thread safety
        - async/await for all public methods
        - URLSession for networking
        - Proper error handling with typed errors

        Args:
            spec: Actor specification

        Returns:
            Swift source code
        """
        actor_name = f"{spec.name}Service"
        imports = ["Foundation"]

        code = f"""//
// {actor_name}.swift
// {self.project_name}
//
// Generated by FORGE iOS Harness
//

"""

        # Imports
        for imp in imports:
            code += f"import {imp}\n"

        code += "\n"

        # Error enum
        code += f"""enum {spec.name}ServiceError: Error {{
    case networkError(Error)
    case invalidResponse
    case decodingError(Error)
    case unauthorized
}}

"""

        # Actor declaration
        code += f"actor {actor_name} {{\n"

        # Properties
        if spec.properties:
            code += "    // MARK: - Properties\n\n"
            for prop in spec.properties:
                access_str = f"{prop.access} " if prop.access != "internal" else ""
                var_type = prop.type
                default = f" = {prop.default_value}" if prop.default_value else ""
                code += f"    {access_str}var {prop.name}: {var_type}{default}\n"
            code += "\n"

        # URLSession (private)
        code += "    // MARK: - Dependencies\n\n"
        code += "    private let session: URLSession\n"
        for dep in spec.dependencies:
            code += f"    private let {self._camel_case(dep)}: {dep}\n"
        code += "\n"

        # Initializer
        code += "    // MARK: - Initialization\n\n"
        if spec.dependencies:
            params = ["session: URLSession = .shared"]
            params.extend([f"{self._camel_case(dep)}: {dep}" for dep in spec.dependencies])
            code += f"    init({', '.join(params)}) {{\n"
            code += "        self.session = session\n"
            for dep in spec.dependencies:
                camel = self._camel_case(dep)
                code += f"        self.{camel} = {camel}\n"
            code += "    }\n"
        else:
            code += "    init(session: URLSession = .shared) {\n"
            code += "        self.session = session\n"
            code += "    }\n"
        code += "\n"

        # Methods
        if spec.methods:
            code += "    // MARK: - Methods\n\n"
            for method in spec.methods:
                code += self._generate_method(method, indent="    ")
                code += "\n"

        code += "}\n"

        return code

    def generate_view(self, spec: ViewSpec) -> str:
        """
        Generate SwiftUI view with proper state management.

        Pattern:
        - SwiftUI view with @State/@Environment
        - ViewModel injected via @Environment or init
        - Loading/error states
        - Proper navigation

        Args:
            spec: View specification

        Returns:
            Swift source code
        """
        view_name = f"{spec.name}View"
        imports = ["SwiftUI"]

        code = f"""//
// {view_name}.swift
// {self.project_name}
//
// Generated by FORGE iOS Harness
//

"""

        # Imports
        for imp in imports:
            code += f"import {imp}\n"

        code += "\n"

        # View declaration
        code += f"struct {view_name}: View {{\n"

        # ViewModel
        code += "    // MARK: - Properties\n\n"
        code += f"    @State private var viewModel: {spec.viewmodel_name}\n"
        code += "\n"

        # Initializer
        code += "    // MARK: - Initialization\n\n"
        code += f"    init(viewModel: {spec.viewmodel_name}) {{\n"
        code += "        self.viewModel = viewModel\n"
        code += "    }\n"
        code += "\n"

        # Body
        code += "    // MARK: - Body\n\n"
        code += "    var body: some View {\n"

        if spec.has_navigation:
            code += "        NavigationStack {\n"
            code += "            content\n"
            code += f'                .navigationTitle("{spec.name}")\n'
            code += "        }\n"
        else:
            code += "        content\n"

        code += "    }\n"
        code += "\n"

        # Content view
        code += "    // MARK: - Content\n\n"
        code += "    @ViewBuilder\n"
        code += "    private var content: some View {\n"

        if spec.has_loading_state:
            code += "        if viewModel.isLoading {\n"
            code += "            ProgressView()\n"

        if spec.has_error_state:
            code += "        } else if let error = viewModel.error {\n"
            code += "            errorView(error)\n"

        code += "        } else {\n"
        code += "            mainContent\n"
        code += "        }\n"
        code += "    }\n"
        code += "\n"

        # Main content
        code += "    @ViewBuilder\n"
        code += "    private var mainContent: some View {\n"
        code += "        VStack {\n"
        code += f'            Text("{spec.name}")\n'
        code += "                .font(.title)\n"
        code += "            // NOTE: Add view content here\n"
        code += "        }\n"
        code += "    }\n"

        # Error view
        if spec.has_error_state:
            code += "\n"
            code += "    @ViewBuilder\n"
            code += "    private func errorView(_ error: Error) -> some View {\n"
            code += "        ContentUnavailableView {\n"
            code += '            Label("Error", systemImage: "exclamationmark.triangle")\n'
            code += "        } description: {\n"
            code += "            Text(error.localizedDescription)\n"
            code += "        } actions: {\n"
            code += '            Button("Retry") {\n'
            code += "                // NOTE: Implement retry logic\n"
            code += "            }\n"
            code += "        }\n"
            code += "    }\n"

        code += "}\n"
        code += "\n"

        # Preview
        code += "#Preview {\n"
        code += f"    {view_name}(viewModel: {spec.viewmodel_name}())\n"
        code += "}\n"

        return code

    def _generate_method(self, method: Method, indent: str = "") -> str:
        """Generate method code."""
        access_str = f"{method.access} " if method.access != "internal" else ""
        async_str = "async " if method.is_async else ""
        throws_str = "throws " if method.throws else ""

        params_str = ""
        if method.parameters:
            params = [f"{name}: {typ}" for name, typ in method.parameters]
            params_str = ", ".join(params)

        return_str = f" -> {method.return_type}" if method.return_type != "Void" else ""

        code = f"{indent}{access_str}func {method.name}({params_str}) {async_str}{throws_str}{return_str} {{\n"

        # Add body with proper indentation
        for line in method.body.split("\n"):
            code += f"{indent}    {line}\n"

        code += f"{indent}}}\n"

        return code

    def _camel_case(self, text: str) -> str:
        """Convert to camelCase."""
        # Remove "Service" suffix if present
        text = text.replace("Service", "")
        # Lowercase first letter
        return text[0].lower() + text[1:] if text else text
